/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.background;
import Controller.Control;
import Controller.HomeController;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
//import view.ChangePasswords;
/**
 *
 * @author PhelanUX
 */
public class Home extends JFrame {


    public Home() {
        initComponents();       
        setTime();
       labelName.setText("Chào mừng: "+Control.getInstance().getName());
       //System.out.print(Control.getInstance().getIdquan());
      intt();
       
    }
    public void intt(){
        if(Control.getInstance().getRole()==3){
            EmployeeBtn.setEnabled(false);
            EmployeeBtn.setVisible(false);
            RevenueBtn.setEnabled(false);
            RevenueBtn.setVisible(false);
            EditDrinkBtn.setVisible(false);
            EditDrinkBtn.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RevenueBtn = new javax.swing.JToggleButton();
        LogOutBtn = new javax.swing.JToggleButton();
        MenuBtn = new javax.swing.JToggleButton();
        EmployeeBtn = new javax.swing.JToggleButton();
        ChangePWBtn = new javax.swing.JButton();
        labelName = new javax.swing.JLabel();
        EditDrinkBtn = new javax.swing.JToggleButton();
        textDate = new javax.swing.JLabel();
        textTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lí quán cafe");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 700, 90));

        RevenueBtn.setBackground(new java.awt.Color(0, 102, 102));
        RevenueBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        RevenueBtn.setText("Doanh Thu");
        RevenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RevenueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, 40));

        LogOutBtn.setBackground(new java.awt.Color(255, 0, 51));
        LogOutBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        LogOutBtn.setText("Đăng xuất");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LogOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 140, 40));

        MenuBtn.setBackground(new java.awt.Color(0, 102, 102));
        MenuBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        MenuBtn.setForeground(new java.awt.Color(51, 51, 51));
        MenuBtn.setText("Danh sách đồ uống");
        MenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBtnActionPerformed(evt);
            }
        });
        jPanel1.add(MenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 220, 40));

        EmployeeBtn.setBackground(new java.awt.Color(0, 102, 102));
        EmployeeBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        EmployeeBtn.setText("Nhân Viên");
        EmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EmployeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 150, 40));

        ChangePWBtn.setBackground(new java.awt.Color(0, 102, 102));
        ChangePWBtn.setText("Đổi mật khẩu");
        ChangePWBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePWBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ChangePWBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, 40));

        labelName.setText("jLabel2");
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 140, -1));

        EditDrinkBtn.setBackground(new java.awt.Color(0, 102, 102));
        EditDrinkBtn.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        EditDrinkBtn.setForeground(new java.awt.Color(51, 51, 51));
        EditDrinkBtn.setText("Chỉnh sửa đồ uống");
        EditDrinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDrinkBtnActionPerformed(evt);
            }
        });
        jPanel1.add(EditDrinkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 250, 40));

        textDate.setBackground(new java.awt.Color(255, 255, 255));
        textDate.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textDate.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        textTime.setBackground(new java.awt.Color(255, 255, 255));
        textTime.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textTime.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

   

    
   
    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        int result =JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        Control.getInstance().setLogoutt(textTime.getText().substring(0, 8));
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalTime startTime = LocalTime.parse(Control.getInstance().getCurrent(), formatter);
        LocalTime endTime = LocalTime.parse(Control.getInstance().getLogoutt(), formatter);
        long hoursDifference = ChronoUnit.HOURS.between(endTime, startTime);
         int hoursDifferenceI = (int) hoursDifference;
        if (result == JOptionPane.YES_OPTION){
            HomeController hc= new HomeController();
            hc.AddHours(hoursDifferenceI, Control.getInstance().getName());
            Login LoginFrame =new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
            //System.out.print(Control.getInstance().getLogoutt());
        }
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void RevenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueBtnActionPerformed
                    Revenue ReFrame =new Revenue();
                    ReFrame.setVisible(true);
                    ReFrame.pack();
                    ReFrame.setLocationRelativeTo( null);//c:null
                    this.dispose();
    }//GEN-LAST:event_RevenueBtnActionPerformed

    private void MenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBtnActionPerformed
                    Menuu MFrame =new Menuu();
                    MFrame.setVisible(true);
                    MFrame.pack();
                    MFrame.setLocationRelativeTo( null);//c:null
                    this.dispose();
    }//GEN-LAST:event_MenuBtnActionPerformed

    private void EmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeBtnActionPerformed
       
        Employee e =new Employee();
        e.setVisible(true);
        e.pack();
        e.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_EmployeeBtnActionPerformed

    private void ChangePWBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePWBtnActionPerformed
        ChangePasswords c=new ChangePasswords();
        c.setVisible(true);
        c.pack();
        this.dispose();
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_ChangePWBtnActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
        int result =JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (result == JOptionPane.YES_OPTION){
            Login LoginFrame =new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
        }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ESCAPE){
        int result =JOptionPane.showOptionDialog(null, "Bạn chắc chắn muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (result == JOptionPane.YES_OPTION){
            Login LoginFrame =new Login();
            LoginFrame.setVisible(true);
            LoginFrame.pack();
            LoginFrame.setLocationRelativeTo(null);
            this.dispose();
        }
        }
    }//GEN-LAST:event_formKeyPressed

    private void EditDrinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDrinkBtnActionPerformed
        EditDrink ReFrame =new EditDrink();
                    ReFrame.setVisible(true);
                    ReFrame.pack();
                    ReFrame.setLocationRelativeTo( null);//c:null
                    this.dispose();
    }//GEN-LAST:event_EditDrinkBtnActionPerformed

    private void setTime(){
        
        new Thread(new Runnable(){
            @Override
            public void run(){
                while(true){
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                     Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("HH:mm:ss aa ");
                    SimpleDateFormat df = new SimpleDateFormat("dd-MM-yy");
                    SimpleDateFormat df1 =new SimpleDateFormat("EEEE");
                    String time = tf.format(date);
                    textTime.setText(time.split(" ")[0] + " " + time.split(" ")[1]);
                    textDate.setText(df.format(date));
                    
                }
            }           
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangePWBtn;
    private javax.swing.JToggleButton EditDrinkBtn;
    private javax.swing.JToggleButton EmployeeBtn;
    private javax.swing.JToggleButton LogOutBtn;
    private javax.swing.JToggleButton MenuBtn;
    private javax.swing.JToggleButton RevenueBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel textDate;
    private javax.swing.JLabel textTime;
    // End of variables declaration//GEN-END:variables


}

