/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import Controller.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import java.time.LocalDate;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
/**
 *
 * @author PhelanUX
 */
public class Revenue extends javax.swing.JFrame {

    /**
     * Creates new form Revenue
     */
    private double totalweek;
    private double totaldate;
    private double totalmonth;
    public Revenue() {
        initComponents();
        init();
        setTotalDate();
        setTotalMonth();
        setTotalWeek();
        setCurrentMonth();
    }
    private void init(){
        setTime();
        
    }
    private void setCurrentMonth(){
        int currentMonth = LocalDate.now().getMonthValue();
        int currentYear = LocalDate.now().getYear();
        RevenueController rc= new RevenueController();
                DefaultCategoryDataset dataset = rc.getRevenueDatasetCurrent();
                JFreeChart barChart = ChartFactory.createBarChart(
                "Doanh thu theo ngày (" + currentMonth + "/" + currentYear + ")", // Tiêu đề biểu đồ
                "Ngày", // Tiêu đề trục X
                "Doanh thu (VNĐ)", // Tiêu đề trục Y
                dataset // Dữ liệu
                );
                CategoryPlot plot = (CategoryPlot) barChart.getPlot();
                BarRenderer renderer = (BarRenderer) plot.getRenderer();

                // Hiển thị giá trị trên mỗi cột
                renderer.setDefaultItemLabelsVisible(true); // Hiển thị nhãn
                renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator());
                renderer.setDefaultItemLabelFont(new Font("SansSerif", Font.BOLD, 12));
                renderer.setDefaultItemLabelPaint(Color.BLACK);
                 ChartPanel chartPanel = new ChartPanel(barChart);
                chartPanel.setPreferredSize(new Dimension(600,400)); // Kích thước của biểu đồ
               
                jPanel2.setLayout(new BorderLayout()); // Đặt layout nếu chưa có
                jPanel2.add(chartPanel, BorderLayout.CENTER); // 
    }
    private void setTotalDate(){
        RevenueController re =new RevenueController();
        re.SelectTotalDay(Control.getInstance().getIdquan());
        
        TotalDate.setText(re.getTotalDate());
        if(TotalDate.getText().equals("")){
            TotalDate.setText("0.0");
        }
        
    }
    private void setTotalWeek(){
        RevenueController re1 =new RevenueController();
        re1.SelectTotalWeek(Control.getInstance().getIdquan());
        TotalWeek.setText(re1.getTotalWeek());
        if(TotalWeek.getText().equals("")){
            TotalWeek.setText("0.0");
        }
        
    }
    private void setTotalMonth(){
        RevenueController re1 =new RevenueController();
        re1.SelectTotalMonth(Control.getInstance().getIdquan());
        TotalMonth.setText(re1.getTotalMonth());
       if(TotalMonth.getText().equals("")){
            TotalMonth.setText("0.0");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        TotalDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TotalWeek = new javax.swing.JTextField();
        jTextTime2 = new javax.swing.JLabel();
        jTextDate2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TotalMonth = new javax.swing.JTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        RevenueMonBtn = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        FindMonthText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnFind = new javax.swing.JToggleButton();
        ComboBoxYear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doanh thu");

        jToggleButton1.setBackground(new java.awt.Color(0, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setText("Trở về");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Doanh thu hôm nay:");

        TotalDate.setEditable(false);
        TotalDate.setBackground(new java.awt.Color(255, 255, 255));
        TotalDate.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        TotalDate.setForeground(new java.awt.Color(51, 51, 51));
        TotalDate.setText("0.0");
        TotalDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Doanh thu cả tuần:");

        TotalWeek.setEditable(false);
        TotalWeek.setBackground(new java.awt.Color(255, 255, 255));
        TotalWeek.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        TotalWeek.setForeground(new java.awt.Color(51, 51, 51));
        TotalWeek.setText("0.0");
        TotalWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalWeekActionPerformed(evt);
            }
        });

        jTextTime2.setBackground(new java.awt.Color(255, 255, 255));
        jTextTime2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextTime2.setForeground(new java.awt.Color(0, 0, 0));

        jTextDate2.setBackground(new java.awt.Color(255, 255, 255));
        jTextDate2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jTextDate2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Doanh thu cả tháng:");

        TotalMonth.setEditable(false);
        TotalMonth.setBackground(new java.awt.Color(255, 255, 255));
        TotalMonth.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        TotalMonth.setForeground(new java.awt.Color(51, 51, 51));
        TotalMonth.setText("0.0");
        TotalMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalMonthActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(0, 102, 102));
        jToggleButton2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("Doanh Thu Chi Tiết");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        RevenueMonBtn.setBackground(new java.awt.Color(0, 102, 102));
        RevenueMonBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        RevenueMonBtn.setForeground(new java.awt.Color(255, 255, 255));
        RevenueMonBtn.setText("Doanh thu theo món");
        RevenueMonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueMonBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel5.setText("Tháng cần hiển thị:");

        FindMonthText.setBackground(new java.awt.Color(255, 255, 255));
        FindMonthText.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        FindMonthText.setForeground(new java.awt.Color(51, 51, 51));
        FindMonthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindMonthTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Năm cần hiển thị:");

        BtnFind.setBackground(new java.awt.Color(0, 102, 102));
        BtnFind.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        BtnFind.setForeground(new java.awt.Color(255, 255, 255));
        BtnFind.setText("Hiển thị");
        BtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindActionPerformed(evt);
            }
        });

        ComboBoxYear.setBackground(new java.awt.Color(102, 102, 102));
        ComboBoxYear.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080", "2081", "2082", "2083", "2084", "2085", "2086", "2087", "2088", "2089", "2090", "2091", "2092", "2093", "2094", "2095", "2096", "2097", "2098", "2099", "2100" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TotalMonth))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TotalWeek))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TotalDate, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RevenueMonBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(FindMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextTime2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextDate2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTime2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RevenueMonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FindMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(BtnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doanh Thu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
                    RevenueController re=new RevenueController();
                    re.Back();
                    this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void TotalDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDateActionPerformed
        
    }//GEN-LAST:event_TotalDateActionPerformed

    private void TotalWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalWeekActionPerformed

    private void TotalMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalMonthActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        RevenueController re=new RevenueController();
        re.RevenueDetails();
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void RevenueMonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueMonBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RevenueMonBtnActionPerformed

    private void FindMonthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindMonthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindMonthTextActionPerformed

    private void BtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindActionPerformed
        
       if(FindMonthText.getText().equals("")){
                String selectedMonth = (String) ComboBoxYear.getSelectedItem();
                int year = Integer.parseInt(selectedMonth);
                RevenueController rc= new RevenueController();
                DefaultCategoryDataset dataset = rc.getRevenueDatasetYear(year);
                JFreeChart barChart = ChartFactory.createBarChart(
                "Doanh thu theo tháng (" + year + ")", // Tiêu đề biểu đồ
                "Tháng", // Tiêu đề trục X
                "Doanh thu (VNĐ)", // Tiêu đề trục Y
                dataset // Dữ liệu
                );
                CategoryPlot plot = (CategoryPlot) barChart.getPlot();
                BarRenderer renderer = (BarRenderer) plot.getRenderer();

                // Hiển thị giá trị trên mỗi cột
                renderer.setDefaultItemLabelsVisible(true); // Hiển thị nhãn
                renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator());
                renderer.setDefaultItemLabelFont(new Font("SansSerif", Font.BOLD, 12));
                renderer.setDefaultItemLabelPaint(Color.BLACK);

                 ChartPanel chartPanel = new ChartPanel(barChart);
                chartPanel.setPreferredSize(new Dimension(600,400)); // Kích thước của biểu đồ
               
                jPanel2.setLayout(new BorderLayout()); // Đặt layout nếu chưa có
                jPanel2.add(chartPanel, BorderLayout.CENTER); // 
                BtnFind.setSelected(false);
            }else{
                int month= Integer.parseInt(FindMonthText.getText());
                String selectedYear = (String) ComboBoxYear.getSelectedItem();
                int year = Integer.parseInt(selectedYear);
            if(month<1 || month >12){
                 JOptionPane.showMessageDialog(new JFrame(),"Tháng nhập vào phải từ 1 đến 12","Error", JOptionPane.ERROR_MESSAGE);
            }else{
                RevenueController rc= new RevenueController();
                DefaultCategoryDataset dataset = rc.getRevenueDataset(month, year);
                JFreeChart barChart = ChartFactory.createBarChart(
                "Doanh thu theo ngày (" + month + "/" + year + ")", // Tiêu đề biểu đồ
                "Ngày", // Tiêu đề trục X
                "Doanh thu (VNĐ)", // Tiêu đề trục Y
                dataset // Dữ liệu
                );
                CategoryPlot plot = (CategoryPlot) barChart.getPlot();
                BarRenderer renderer = (BarRenderer) plot.getRenderer();

                // Hiển thị giá trị trên mỗi cột
                renderer.setDefaultItemLabelsVisible(true); // Hiển thị nhãn
                renderer.setDefaultItemLabelGenerator(new StandardCategoryItemLabelGenerator());
                renderer.setDefaultItemLabelFont(new Font("SansSerif", Font.BOLD, 12));
                renderer.setDefaultItemLabelPaint(Color.BLACK);
                 ChartPanel chartPanel = new ChartPanel(barChart);
                chartPanel.setPreferredSize(new Dimension(600,400)); // Kích thước của biểu đồ
               
                jPanel2.setLayout(new BorderLayout()); // Đặt layout nếu chưa có
                jPanel2.add(chartPanel, BorderLayout.CENTER); // 
                BtnFind.setSelected(false);
            }
        }
        
    }//GEN-LAST:event_BtnFindActionPerformed
    private void setTime(){
        
        new Thread(new Runnable(){
            @Override
            public void run(){
                while(true){
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                     Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("HH:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yy");
                    
                    String time = tf.format(date);
                    jTextTime2.setText(time.split(" ")[0] + " " + time.split(" ")[1]);
                    jTextDate2.setText(df.format(date));
                    
                }
            }           
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Revenue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Revenue().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnFind;
    private javax.swing.JComboBox<String> ComboBoxYear;
    private javax.swing.JTextField FindMonthText;
    private javax.swing.JToggleButton RevenueMonBtn;
    private javax.swing.JTextField TotalDate;
    private javax.swing.JTextField TotalMonth;
    private javax.swing.JTextField TotalWeek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jTextDate2;
    private javax.swing.JLabel jTextTime2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
